# Generated by Django 5.1.6 on 2025-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customuser_brand_name_customuser_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
